import {
  sliderimg1,
  sliderimg2,
  humidity,
  windnight,
  sunrise,
  sunset,
  clouds,
  uv,
  pressure,
  cloudynandsun,
  rainy,
  sunny,
} from "../constants/index";
export const Today = [
  {
    id: 1,
    Text: "Sunday",
    lighttext: "1:30AM",
    image: sliderimg1,
    descr: "few clouds",
    temp: "30°",
  },
  {
    id: 2,
    Text: "Sunday",
    lighttext:'2:30AM',
    image: sliderimg1,
    descr: "few clouds",
    temp:'30°'
},
{
    id: 3,
    Text: "Sunday",
    lighttext:'3:30AM',
    image: sliderimg1,
    descr: "few clouds",
    temp:'30°'
},
{
    id: 4,
    Text: "Sunday",
    lighttext:'4:30AM',
    image: sliderimg2,
    descr: "Clear sky",
    temp:'30°'
},
];
export const Todayshighlights = [
  {
    id: 1,
    Text: "Humidity",
    image: humidity,
    temp: "96",
    sign: "%",
  },
  {
    id: 2,
    Text: "Wind Speed",
    image: windnight,
    temp: "1.5",
    sign: "m/s",
  },
  {
    id: 3,
    Text1: "Sunrise",
    image1: sunrise,
    time1: "5:52 AM",
    text2: "Sunset",
    image2: sunset,
    time2: "6:52 PM",
  },
  {
    id: 4,
    Text: "Clouds",
    image: clouds,
    temp: "20",
    sign: "%",
  },
  {
    id: 5,
    Text: "UV index",
    image: uv,
    temp: "0",
    sign: "",
  },
  {
    id: 6,
    Text: "Pressure",
    image: pressure,
    temp: "1005",
    sign: "nPa",
  },
];
export const thisweek = [
  {
    id: 1,
    day: "Sunday",
    image: cloudynandsun,
    descr: "few clouds",
    hightemp: "38",
    lowtemp: "30",
  },
  {
    id: 2,
    day: "Monday",
    image: rainy,
    descr: "moderate rain",
    hightemp: "37",
    lowtemp: "28",
  },
  {
    id: 3,
    day: "Tuesday",
    image: rainy,
    descr: "moderate rain",
    hightemp: "29",
    lowtemp: "26",
  },
  {
    id: 4,
    day: "Wenesday",
    image: rainy,
    descr: "light rain",
    hightemp: "35",
    lowtemp: "36",
  },
  {
    id: 5,
    day: "Thursday",
    image: sunny,
    descr: "Clear Sky",
    hightemp: "39",
    lowtemp: "30",
  },
  {
    id: 6,
    day: "Friday",
    image: rainy,
    descr: "light rain",
    hightemp: "38",
    lowtemp: "27",
  },
  {
    id: 7,
    day: "Saturday",
    image: rainy,
    descr: "light rain",
    hightemp: "36",
    lowtemp: "26",
  },
  {
    id: 8,
    day: "Friday",
    image: rainy,
    descr: "moderate rain",
    hightemp: "37",
    lowtemp: "26",
  },
];
